### ISSUE TITLE
Implement prepend feature

### ISSUE THREAD

**Issue by ArtemkaKun** [julien-deramond/update-issue-body#3]
Hi, good job on this action. I also would like to see a prepend feature to insert new content on top of the issue's body.

**Comment by julien-deramond** [comment]
Hey @ArtemkaKun 
This is a good idea, I'm trying some things via https://github.com/julien-deramond/update-issue-body/pull/4. As soon as it is ready, it'll be embedded in a v1.1 🚀

**Comment by julien-deramond** [comment]
It's released in [v1.1.0](https://github.com/julien-deramond/update-issue-body/releases/tag/v1.1.0). Don't hesitate to tell me if there are some issues with the new version or the old one, I'm not yet really aware of the GH actions release and versioning systems 😇
